betelgeuse: "tests/foreman/ -v -m 'build_sanity'"
broker[docker]: "tests/foreman/ -v -m 'build_sanity'"
cryptography: "tests/foreman/ -v -m 'build_sanity'"
deepdiff: "tests/foreman/ -v -m 'build_sanity'"
dynaconf[vault]: "tests/foreman/ -v -m 'build_sanity'"
fauxfactory: "tests/foreman/ -v -m 'build_sanity'"
flake8: "tests/foreman/ -v -m 'build_sanity'"
jinja2: "tests/foreman/ -v -m 'build_sanity'"
manage: "tests/foreman/ -v -m 'build_sanity'"
manifester: "tests/foreman/ -v -m 'build_sanity'"
navmazing: "tests/foreman/ -v -m 'build_sanity'"
pre-commit: "tests/foreman/ -v -m 'build_sanity'"
productmd: "tests/foreman/ -v -m 'build_sanity'"
pyotp: "tests/foreman/ -v -m 'build_sanity'"
pytest-cov: "tests/foreman/ -v -m 'build_sanity'"
pytest-ibutsu: "tests/foreman/ -v -m 'build_sanity'"
pytest-mock: "tests/foreman/ -v -m 'build_sanity'"
pytest-reportportal: "tests/foreman/ -v -m 'build_sanity'"
pytest-services: "tests/foreman/ -v -m 'build_sanity'"
pytest-xdist: "tests/foreman/ -v -m 'build_sanity'"
pytest: "tests/foreman/ -v -m 'build_sanity'"
python-box: "tests/foreman/ -v -m 'build_sanity'"
PyYAML: "tests/foreman/ -v -m 'build_sanity'"
redis: "tests/foreman/ -v -m 'build_sanity'"
requests: "tests/foreman/ -v -m 'build_sanity'"
sphinx-autoapi: "tests/foreman/ -v -m 'build_sanity'"
sphinx: "tests/foreman/ -v -m 'build_sanity'"
tenacity: "tests/foreman/ -v -m 'build_sanity'"
testimony: "tests/foreman/ -v -m 'build_sanity'"
wait-for: "tests/foreman/ -v -m 'build_sanity'"
wrapanapi: "tests/foreman/ -v -m 'build_sanity'"