broker[docker]: "tests/foreman/ -v -k 'test_host_registration_end_to_end or test_positive_erratum_applicability or test_positive_upload_content'"
deepdiff: "tests/foreman/endtoend/test_api_endtoend.py -v -k 'test_positive_get_links'"
dynaconf[vault]: "tests/foreman/ -v -m 'build_sanity'"
fauxfactory: "tests/foreman/ -v -m 'build_sanity'"
manifester: "tests/foreman/api/test_subscription.py -v -k 'test_positive_create_after_refresh'"
navmazing: "tests/foreman/ui/test_repository.py -v -k 'test_positive_create_as_non_admin_user'"
pyotp: "tests/foreman/ui/test_ldap_authentication.py -v -k 'test_positive_login_user_password_otp'"
pytest-ibutsu: "tests/foreman/ -v -m 'build_sanity'"
pytest-mock: "tests/foreman/ -v -m 'build_sanity'"
pytest-reportportal: "tests/foreman/ -v -m 'build_sanity'"
pytest-xdist: "tests/foreman/ -v -m 'build_sanity'"
pytest: "tests/foreman/ -v -m 'build_sanity'"
python-box: "tests/foreman/ -v -m 'build_sanity'"
requests: "tests/foreman/cli/test_repository.py -v -k 'test_file_repo_contains_only_newer_file'"
wait-for: "tests/foreman/api/test_reporttemplates.py -v -k 'test_positive_schedule_entitlements_report'"
wrapanapi: "tests/foreman/longrun/test_provisioning_computeresource.py -v -k 'test_positive_provision_vmware_with_host_group'"

