### The auto branching workflow triggered through dispatch request from CI
name: auto-branching

# Run on workflow dispatch from CI
on:
  workflow_dispatch:
    inputs:
      target_branch:
        type: string
        description: branch to be created from the master


jobs:
  auto-branching:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create the target branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ github.event.inputs.target_branch }}

      - name: Create label for the target branch 
        run: |
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/labels \
              -d "{\"name\":\"${{ github.event.inputs.target_branch }}\",\"color\":\"fbca04\"}"
