### The prt result workflow triggered through dispatch request from CI
name: post-prt-result

# Run on workflow dispatch from CI
on:
  workflow_dispatch:
    inputs:
      pr_number:
        type: string
        description: pr number for PRT run
      build_number:
        type: string
        description: build number for PRT run
      pytest_result:
        type: string
        description: pytest summary result line
      build_status:
        type: string
        description: status of jenkins build e.g. success, unstable or error


jobs:
  post-the-prt-result:
    runs-on: ubuntu-latest

    steps:
      - name: Add last PRT result into the github comment
        id: add-prt-comment
        if: ${{ always() && github.event.inputs.pytest_result != '' }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Build Number: ${{ github.event.inputs.build_number }}
            Build Status: ${{ github.event.inputs.build_status }}
            Test Result : ${{ github.event.inputs.pytest_result }}
          pr_number: ${{ github.event.inputs.pr_number }}
          GITHUB_TOKEN: ${{ secrets.CHERRYPICK_PAT }}

      - name: Add the PRT passed/failed labels
        id: prt-status
        if: ${{ always() && github.event.inputs.build_status != '' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.CHERRYPICK_PAT }}
          script: |
            const status = "${{ github.event.inputs.build_status }}";
            if (status === "SUCCESS") {
              github.rest.issues.addLabels({
                issue_number:  ${{ github.event.inputs.pr_number }},
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels:["PRT-Passed"]
              })
              core.setOutput('result', 'PRT-Passed');
            }
            else{
              github.rest.issues.addLabels({
                issue_number: ${{ github.event.inputs.pr_number }},
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ["PRT-Failed"]
              })
              core.setOutput('result', 'PRT-Failed');
            }
      - name: Remove the label if
        if: ${{ always() && github.event.inputs.build_status != '' }}
        uses: actions/github-script@v7
        with:
          script: |
            const issue = await github.rest.issues.get({
              owner: context.issue.owner,
              repo: context.issue.repo,
              issue_number:  ${{ github.event.inputs.pr_number }},
            });
            const status = "${{ github.event.inputs.build_status }}";
            if (status === "SUCCESS") {
              const labelExists = issue.data.labels.find(({ name }) =>
                 name === "PRT-Failed"
              );
              if (labelExists){
              github.rest.issues.removeLabels({
                issue_number: ${{ github.event.inputs.pr_number }},
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ["PRT-Failed"]
                })
              }
            }

