# CI stages to execute against Pull Requests
name: Robottelo - CI

on:
  push:
  pull_request:
    types: ["opened", "synchronize"]

jobs:
    prt_labels:
      name: remove the PRT label, if it is a new commit
      runs-on: ubuntu-latest
      steps:
        - name: Fetch the PRT status
          id: outcome
          uses: omkarkhatavkar/wait-for-status-checks@main
          with:
            ref: ${{ github.head_ref }}
            context: 'Robottelo-Runner'
            wait-interval: 60
            count: 100
  
        - name: Check the PRT status
          if: always()
          run: |
            if [ ${{ steps.outcome.outputs.result }} == 'success' ]; then
              echo "Status check passed!"
            else
              echo "Status check failed!"
            fi
        
        - name: run this always
          if: always()
          run: echo ${{ steps.outcome.outputs.result }} 
            
        - name: remove the PRT Passed/Failed label for new commit
          if: always() && ${{steps.outcome.outputs.result}} == 'not found'
          uses: actions/github-script@v7
          with:
            github-token: ${{ secrets.CHERRYPICK_PAT }}
            script: |
              const prNumber = ${{ github.event.number }};
              const issue = await github.rest.issues.get({
                owner: context.issue.owner,
                repo: context.issue.repo,
                issue_number: prNumber,
              });
              const labelsToRemove = ['PRT-Failed', 'PRT-Passed'];
              const labelsToRemoveFiltered = labelsToRemove.filter(label => issue.data.labels.some(({ name }) => name === label));
              if (labelsToRemoveFiltered.length > 0) {
                await Promise.all(labelsToRemoveFiltered.map(async label => {
                  await github.rest.issues.removeLabel({
                    issue_number: prNumber,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    name: label
                  });
                }));
              }
