# CI stages to execute against Pull Requests
name: Search GH PR's based on title

on:
  pull_request:
    types: ["opened", "synchronize", "reopened"]

jobs:
  search_for_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Search for the pull request
        id: search
        uses: omkarkhatavkar/search-github-prs@main
        with:
          repo: 'satelliteqe/robottelo'
          title: '[6.15.z] Sync project dependencies'
      - name: Check the result
        run: |
          echo "Result: ${{ steps.search.outputs.result }}"
          if [ ${{ steps.search.outputs.result }} == 'success' ]; then
            echo "The PR is found"
            echo "${{ steps.search.outputs.details }}"
          else
            echo "Failed to find the PR"
          fi
