name: Example Workflow

on:
  pull_request_target:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read labels from YAML
        id: read-labels
        run: |
          LABELS=$(python3 -c "import yaml; print(' '.join(yaml.safe_load(open('./.github/labels.yaml'))['pre_commit_bot_labels']))")
          echo "::set-output name=LABELS::$LABELS"
    
      - name: apply supported version labels to cherry-pick PRs created by the pre-commit-bot.
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.CHERRYPICK_PAT }}
          script: |
            const labels = ${{ steps.read-labels.outputs.LABELS }};
            const prNumber = '${{ github.event.number }}';
            github.rest.issues.addLabels({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: labels.split(' ')
            });
